"use client";

import { useDeferredValue, useMemo, useState } from "react";
import { Building2, HardHat, Mail, Phone, Search, UsersRound } from "lucide-react";
import { Input } from "@/components/ui/input";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";

type Contractor = { name: string; trade: string; phone: string; email: string; status: "Aktiven" | "Ponudba" };

export function ContractorsWorkspace({ contractors }: { contractors: Contractor[] }) {
  const [query, setQuery] = useState("");
  const [trade, setTrade] = useState("Vse stroke");
  const deferredQuery = useDeferredValue(query.trim().toLocaleLowerCase("sl"));
  const trades = useMemo(() => ["Vse stroke", ...new Set(contractors.map((contractor) => contractor.trade))], [contractors]);
  const filtered = useMemo(() => contractors.filter((contractor) => (!deferredQuery || `${contractor.name} ${contractor.trade}`.toLocaleLowerCase("sl").includes(deferredQuery)) && (trade === "Vse stroke" || contractor.trade === trade)), [contractors, deferredQuery, trade]);

  return <div className="space-y-5"><section className="grid gap-3 sm:grid-cols-3" aria-label="Povzetek izvajalcev">{[{ label: "Vsi kontakti", value: contractors.length, icon: UsersRound }, { label: "Aktivni izvajalci", value: contractors.filter((item) => item.status === "Aktiven").length, icon: HardHat }, { label: "Različne stroke", value: new Set(contractors.map((item) => item.trade)).size, icon: Building2 }].map((metric) => <div key={metric.label} className="rounded-2xl border bg-card p-5 shadow-sm"><div className="flex items-center justify-between"><div><p className="text-sm text-muted-foreground">{metric.label}</p><p className="mt-2 text-2xl font-bold">{metric.value}</p></div><span className="grid size-10 place-items-center rounded-xl bg-accent"><metric.icon className="size-5" /></span></div></div>)}</section><section className="flex flex-col gap-3 rounded-2xl border bg-card p-4 shadow-sm sm:flex-row"><div className="relative flex-1"><Search className="absolute left-3.5 top-3.5 size-4 text-muted-foreground" /><Input value={query} onChange={(event) => setQuery(event.target.value)} aria-label="Išči izvajalce" placeholder="Išči izvajalca ali stroko …" className="h-11 pl-10" /></div><Select value={trade} onValueChange={(next) => setTrade(next ?? "Vse stroke")}><SelectTrigger id="contractor-trade" aria-label="Stroka" className="h-11 w-full sm:w-56"><SelectValue /></SelectTrigger><SelectContent>{trades.map((item) => <SelectItem key={item} value={item}>{item}</SelectItem>)}</SelectContent></Select></section>{filtered.length ? <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{filtered.map((contractor) => <article key={contractor.name} className="rounded-2xl border bg-card p-5 shadow-sm"><div className="flex items-start justify-between"><span className="grid size-11 place-items-center rounded-xl bg-accent text-accent-foreground"><HardHat className="size-5" /></span><span className={`rounded-full px-2.5 py-1 text-xs font-medium ${contractor.status === "Aktiven" ? "bg-emerald-50 text-emerald-700" : "bg-amber-50 text-amber-700"}`}>{contractor.status}</span></div><h2 className="mt-4 font-semibold">{contractor.name}</h2><p className="text-sm text-muted-foreground">{contractor.trade}</p><div className="mt-5 space-y-1"><a className="flex min-h-10 items-center gap-2 rounded-lg px-2 text-sm transition-colors hover:bg-muted hover:text-primary" href={`tel:${contractor.phone.replaceAll(" ", "")}`}><Phone className="size-4" />{contractor.phone}</a><a className="flex min-h-10 items-center gap-2 rounded-lg px-2 text-sm transition-colors hover:bg-muted hover:text-primary" href={`mailto:${contractor.email}`}><Mail className="size-4" /><span className="truncate">{contractor.email}</span></a></div></article>)}</div> : <div className="rounded-2xl border border-dashed bg-card p-12 text-center"><p className="font-medium">Ni najdenih izvajalcev</p><p className="mt-1 text-sm text-muted-foreground">Spremeni iskanje ali izbrano stroko.</p></div>}</div>;
}
