"use client";

import { useDeferredValue, useMemo, useState } from "react";
import { FileCheck2, FileClock, Files, FileText, Search, ShieldCheck } from "lucide-react";
import { Input } from "@/components/ui/input";

type ProjectDocument = { name: string; type: string; status: string; updated: string; owner: string };

export function DocumentsWorkspace({ documents }: { documents: ProjectDocument[] }) {
  const [query, setQuery] = useState("");
  const [type, setType] = useState("Vse vrste");
  const deferredQuery = useDeferredValue(query.trim().toLocaleLowerCase("sl"));
  const types = useMemo(() => ["Vse vrste", ...new Set(documents.map((document) => document.type))], [documents]);
  const filtered = useMemo(() => documents.filter((document) => (!deferredQuery || document.name.toLocaleLowerCase("sl").includes(deferredQuery)) && (type === "Vse vrste" || document.type === type)), [deferredQuery, documents, type]);

  return <div className="space-y-5"><section className="grid gap-3 sm:grid-cols-3" aria-label="Povzetek dokumentov">{[{ label: "Vsi dokumenti", value: documents.length, icon: Files }, { label: "Potrjeni", value: documents.filter((item) => item.status === "Potrjeno").length, icon: FileCheck2 }, { label: "V pregledu", value: documents.filter((item) => item.status === "V pregledu").length, icon: FileClock }].map((metric) => <div key={metric.label} className="rounded-2xl border bg-card p-5 shadow-sm"><div className="flex items-center justify-between"><div><p className="text-sm text-muted-foreground">{metric.label}</p><p className="mt-2 text-2xl font-bold">{metric.value}</p></div><span className="grid size-10 place-items-center rounded-xl bg-accent"><metric.icon className="size-5" /></span></div></div>)}</section><section className="flex flex-col gap-3 rounded-2xl border bg-card p-4 shadow-sm sm:flex-row"><div className="relative flex-1"><Search className="absolute left-3.5 top-3.5 size-4 text-muted-foreground" /><Input value={query} onChange={(event) => setQuery(event.target.value)} aria-label="Išči dokumente" placeholder="Išči dokument …" className="h-11 pl-10" /></div><label className="sr-only" htmlFor="document-type">Vrsta datoteke</label><select id="document-type" value={type} onChange={(event) => setType(event.target.value)} className="min-h-11 rounded-lg border bg-background px-3 text-sm outline-none focus-visible:ring-3 focus-visible:ring-ring/50 sm:w-48">{types.map((item) => <option key={item}>{item}</option>)}</select></section>{filtered.length ? <div className="overflow-hidden rounded-2xl border bg-card shadow-sm">{filtered.map((document) => <article key={document.name} className="flex flex-col gap-4 border-b p-5 last:border-0 sm:flex-row sm:items-center"><span className="grid size-10 shrink-0 place-items-center rounded-lg bg-accent"><FileText className="size-5" /></span><div className="min-w-0 flex-1"><h2 className="font-medium">{document.name}</h2><p className="mt-1 text-xs text-muted-foreground">{document.type} · posodobil {document.owner} · {document.updated}</p></div><span className={`inline-flex w-fit items-center gap-1 rounded-full px-2.5 py-1 text-xs font-medium ${document.status === "V pregledu" ? "bg-amber-50 text-amber-700" : "bg-emerald-50 text-emerald-700"}`}><ShieldCheck className="size-3.5" />{document.status}</span></article>)}</div> : <div className="rounded-2xl border border-dashed bg-card p-12 text-center"><p className="font-medium">Ni najdenih dokumentov</p><p className="mt-1 text-sm text-muted-foreground">Spremeni iskalni niz ali vrsto datoteke.</p></div>}</div>;
}
